name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: yournamezara333/digital-twine-gas-turbine

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get commit hash
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push backend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:${{ steps.commit.outputs.sha_short }} ./backend
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:${{ steps.commit.outputs.sha_short }}

      - name: Build and push kafka
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/kafka:${{ steps.commit.outputs.sha_short }} ./kafka
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/kafka:${{ steps.commit.outputs.sha_short }}

      - name: Build and push influxdb
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/influxdb:${{ steps.commit.outputs.sha_short }} ./influxdb
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/influxdb:${{ steps.commit.outputs.sha_short }}

      - name: Build and push mysql
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/mysql:${{ steps.commit.outputs.sha_short }} ./mysql
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/mysql:${{ steps.commit.outputs.sha_short }}